baseURL = "https://blog2.issei.org/"
languageCode = "ja"
title = "或曰"
theme = "pickles"
hasCJKLanguage = "true"
summaryLength = 100

[permalinks]
  "posts" = ":year/:month/:day/:slug"

[params]
  paginate = 5
  hideModifiedDate = true
  hideWordCount = true
  hideReadingTime = true
  twitter = "issei_swe"
  github = "isseis"
  [params.getform]
    endpoint = "a874702f-ed84-4de6-b978-34586da4d849"
    recaptcha_id = "6LcWLsoZAAAAAEXpuHDLCIpM5bemiSMqQsON-ZND"
    for = ['about', 'posts']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "Search"
  url = "https://www.google.co.jp/search?q=site:blog2.issei.org"
  weight = 1

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 3

[[menu.main]]
  name = "Admin"
  url = "/admin/"
  weight = 10
