# Travis CI

dist: focal
addons:
  snaps:
  - hugo

script:
- hugo

deploy:
  provider: firebase
  token:
    secure: WcaMxWyDwwZy75qlkdofp99ztbAJZysy7DTGEE8cC7oHiRhJPYwNKlAgAdGf5z7WPPcGLwkbY1/PNWC4PuwrgiknMENO6aZaQL7xZj0p3eNw7O0827AoELGsLz2dfcLBEer6q4449iHxSJr1PvxURAO7BOn82P7GthIu/YcRKehwtFTBu0TNqjBQ/Ag6cFk1RvI9ypebonFWYJcPUGzlVYvyrypwtkBrLE94mv7XBcaVfra22PIZI0oQQ5YkC036VD6egxAdPc2n55D0b0IuM6LIsACFZkBasoXR+8HnxrU+4As3DS3FzN70VmGxXBqCSD4iGLzXOvIAocXiGp8iX8wr0x9OK60c7Ago5U54cEa5acrtXRKpsXXtSgKOr4SmHbS/QKq3SzX+WZlsnHieDNDfjiOG3TJtVoAq0Ou5/Vh9t7m6KefUAauUhaE5sRv/3FcMb75ukdbVC1eFC5ubpc619Gpa6JS4J5WRJoOEI5Myfo9fzUv+7HT6/mCYz+VXM6nMeskPZveyKhEsEF6EGHv6mlbMZrimPD9C9GLTQ7CSca17EKUa76FF3wg3G8XBWl4ZcNsyiHr7Casz+snsX1wlnsJQvC8MbxKAOQLdJBFqHYZgVbfmSqR4xvspPtxM0dQibXpmtf36XvqIx8rk8Mu6T7xZBw0Ui36UEoLqVXc=
  skip_cleanup: true

notifications:
  slack:
    on_success: always
    on_failure: always
    secure: NAKhI4UZ5uf+kjNocMBtvPdPex/tgkfHe18Tm/b9XLyJnJErY1mA6pgO+nG3BrqyuQ5NazyJyLlzc/offhUCC8F+ouKbHx+m7xfR/9o/xY/QhTYpWmEmTgF4rpe4R4aivQMPRmQeXYUoH4TH271zcM5YTFh2cmu6z++lFK56K/8SmukDwDxCU7pGDubXDYadxTUt6jlmnaHdUd4Cukpz7nEcx4QiMU9qAxH9+MFzHJGfqTk5V9wwjetuorqdl3Ib678/EwppSM5FBgHHvkpPItWF+4zinqxOK7bk/7He0C0tXoty1i3uoLlCelr4qsNvEaHWLiCx6ODMdv9VQViwZ2w/GKMMY0gdXC4fWv9qQ9PfdLxYYjitu/4SykRb/htlMlVn3MRReZqVn/UseF0XK/JHxdteAoglTUCDVw7VbLDhzYYG/yPgRGZfZTjlquDWP2FaAl078IhK5jRGHk5yurn2eSe11wwOCNZofEBpzVnXsAvVnGS/+qOWfmst6KvBXfnBNAc+y3fYsYagHxwm4yD+dlmd+AH5kNNwgjeZAOB7kMxWLJVKLRR6X4dRQgtNVpCqpNBR0v2aIbPu1GwEh7CODgoKq3pVN4dSP96GCUWTpiC3v2W5LM2LkIfBnMa/DOH0Q4NJDhptqYwegONww7ybMJEtiiyh6go+BmMqmTw=
  email: false