os: linux
language: generic

dist: focal
addons:
  snaps:
  - name: hugo
    channel: extended

script:
- hugo
- cp public/index.xml public/feed.xml

deploy:
  provider: firebase
  token:
    secure: WcaMxWyDwwZy75qlkdofp99ztbAJZysy7DTGEE8cC7oHiRhJPYwNKlAgAdGf5z7WPPcGLwkbY1/PNWC4PuwrgiknMENO6aZaQL7xZj0p3eNw7O0827AoELGsLz2dfcLBEer6q4449iHxSJr1PvxURAO7BOn82P7GthIu/YcRKehwtFTBu0TNqjBQ/Ag6cFk1RvI9ypebonFWYJcPUGzlVYvyrypwtkBrLE94mv7XBcaVfra22PIZI0oQQ5YkC036VD6egxAdPc2n55D0b0IuM6LIsACFZkBasoXR+8HnxrU+4As3DS3FzN70VmGxXBqCSD4iGLzXOvIAocXiGp8iX8wr0x9OK60c7Ago5U54cEa5acrtXRKpsXXtSgKOr4SmHbS/QKq3SzX+WZlsnHieDNDfjiOG3TJtVoAq0Ou5/Vh9t7m6KefUAauUhaE5sRv/3FcMb75ukdbVC1eFC5ubpc619Gpa6JS4J5WRJoOEI5Myfo9fzUv+7HT6/mCYz+VXM6nMeskPZveyKhEsEF6EGHv6mlbMZrimPD9C9GLTQ7CSca17EKUa76FF3wg3G8XBWl4ZcNsyiHr7Casz+snsX1wlnsJQvC8MbxKAOQLdJBFqHYZgVbfmSqR4xvspPtxM0dQibXpmtf36XvqIx8rk8Mu6T7xZBw0Ui36UEoLqVXc=
  skip_cleanup: true

notifications:
  slack:
    on_success: always
    on_failure: always
    secure: t2EogMtH1jbiIvKixg4lNvkZwa4m3nVRjcmgI/cFFBPYfB36n5Jyz0ILpOK1uPHHKJYIe65azqqXQ3w/pjvTt63CBRDr3ulZcp7sghGumFXFZS8iKS0GSoTfF3FtWJMuWiIYxwQrUtentVGFCqm54t59XYT8ufA+s01qw01VUz5iSYmYcz47HhFVZ7dP8go1p+UkTA6BcLYTlYdUvnuI++RUrwqTdg70EigNa2Tk0Z2vzerWRiQYlNeOFzpBLF2t3sstecWLuqKzOkqcJFYUCUv6xuCP07QattS2xI7OY9Y3UDSjwb3f7Ca2O2f5sIgvg+/0I2pjuEaOC2bnc1bMMZGxxJ+CCbjTDd07m11I2ravKl6MevkZ03xtGmiSaM/mKgMSsoc04XQekeuXyxMMyZiyr+aQbfUpRXJgk+T8Y6E15lqNFR4OcfEwkPs8QNdFBJXyGkgfYcT8lkcWuejRbRnDY/6INj+dm4iVqQ9mh9FiEHJyYl1YIv2zbxNtrN+/i2siRvfV6A58homrsGO+sDHvqN43zpC8OHxaUx1XY/1x3htz6RZ1VpdvNgOz1mVVhMhj63s/lWQf65qIxi2QH4OWatxHvJf1oA2J+2BldsuMVlPbEXjBg5E0xdVYDhAHhON+9oekXk0wHvpH5EipMtpJx0+93jtrMJMhXdQbBMs=
  email: false
