baseURL = "https://blog2.issei.org/"
languageCode = "ja"
title = "或曰"
theme = "pickles"
hasCJKLanguage = "true"
summaryLength = 100
paginate = 5

[permalinks]
  "posts" = ":year/:month/:day/:slug"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true