name: Firebase

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.82.1'
          extended: true

      - name: Build Site
        run: hugo --cleanDestinationDir --minify
      
      - name: Create Compat RSS
        run: cp public/index.xml public/feed.xml
      
      - name: Archive Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
      
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
          
      - name: Deploy to Firease
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLOG_HUGO_ISSEI }}"
          projectId: blog-hugo-issei
          channelId: live
